#!/usr/bin/env python3
"""Generate deterministic Markdown references from canonical MeaningWire JSON.

Generated pages are presentation artifacts only. Schemas and mappings remain
canonical in their registries and JSON definitions.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_REGISTRY = ROOT / "schemas" / "registry.json"
MAPPING_REGISTRY = ROOT / "mappings" / "registry.json"
OUTPUT_DIR = ROOT / "docs" / "reference" / "generated"
STARLIGHT_OUTPUT_DIR = ROOT / "src" / "content" / "docs" / "reference"
GITHUB_BLOB_ROOT = "https://github.com/MeaningWire/MeaningWire/blob/main"
HEADER = "<!-- GENERATED by tools/generate_reference_docs.py; DO NOT EDIT. -->"


class ReferenceGenerationError(ValueError):
    """Raised when canonical reference inputs are inconsistent."""


def load_json(path: Path) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        raise ReferenceGenerationError(f"cannot read JSON input {path.relative_to(ROOT)}: {exc}") from exc


def repo_link(path: str) -> str:
    return "../../../" + path


def public_source_link(path: str) -> str:
    return f"{GITHUB_BLOB_ROOT}/{path}"


def reference_text(reference: dict[str, Any]) -> str:
    namespace = reference["namespace"]
    identifier = reference["id"]
    version = reference.get("version")
    return f"{namespace}:{identifier}:{version}" if version else f"{namespace}:{identifier}"


def load_schema_records() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    registry = load_json(SCHEMA_REGISTRY)
    records: list[dict[str, Any]] = []
    for entry in registry.get("schemas", []):
        path = ROOT / entry["path"]
        schema = load_json(path)
        if schema.get("$id") != entry["id"]:
            raise ReferenceGenerationError(f"schema ID mismatch for {entry['path']}")
        if schema.get("x-meaningwire-contract-version") != entry["version"]:
            raise ReferenceGenerationError(f"schema version mismatch for {entry['path']}")
        records.append({"entry": entry, "schema": schema})
    records.sort(key=lambda record: record["entry"]["id"])
    return registry, records


def load_mapping_records() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    registry = load_json(MAPPING_REGISTRY)
    records: list[dict[str, Any]] = []
    for entry in registry.get("mappings", []):
        path = ROOT / entry["path"]
        mapping = load_json(path)
        if mapping.get("mapping_id") != entry["mapping_id"]:
            raise ReferenceGenerationError(f"mapping ID mismatch for {entry['path']}")
        if mapping.get("version") != entry["version"]:
            raise ReferenceGenerationError(f"mapping version mismatch for {entry['path']}")
        records.append({"entry": entry, "mapping": mapping})
    records.sort(
        key=lambda record: (
            record["mapping"]["mapping_id"]["namespace"],
            record["mapping"]["mapping_id"]["id"],
            record["mapping"]["version"],
        )
    )
    return registry, records


def schema_reference_lines(source_link: Callable[[str], str]) -> list[str]:
    registry, records = load_schema_records()
    lines = [
        "This page is generated deterministically from `schemas/registry.json` and the registered JSON Schema documents. Edit the canonical schemas or registry, then regenerate this page.",
        "",
        f"Registry version: `{registry['registry_version']}`  ",
        f"Registry maturity: `{registry['maturity']}`",
        "",
        "| Schema | Version | Maturity | Source |",
        "| --- | --- | --- | --- |",
    ]

    for record in records:
        entry = record["entry"]
        schema = record["schema"]
        maturity = schema.get("x-meaningwire-maturity", "UNSPECIFIED")
        lines.append(
            f"| `{entry['id']}` | `{entry['version']}` | `{maturity}` | "
            f"[`{entry['path']}`]({source_link(entry['path'])}) |"
        )

    for record in records:
        entry = record["entry"]
        schema = record["schema"]
        title = schema.get("title", entry["id"])
        description = schema.get("description", "No description supplied.")
        maturity = schema.get("x-meaningwire-maturity", "UNSPECIFIED")
        required = schema.get("required", [])
        required_text = ", ".join(f"`{field}`" for field in required) if required else "none"
        additional = "rejected" if schema.get("additionalProperties") is False else "allowed"
        lines.extend(
            [
                "",
                f"## {title}",
                "",
                description,
                "",
                f"- **ID:** `{entry['id']}`",
                f"- **Version:** `{entry['version']}`",
                f"- **Maturity:** `{maturity}`",
                f"- **Source:** [`{entry['path']}`]({source_link(entry['path'])})",
                f"- **Required top-level fields:** {required_text}",
                f"- **Additional top-level properties:** {additional}",
            ]
        )

    return lines


def mapping_reference_lines(source_link: Callable[[str], str]) -> list[str]:
    registry, records = load_mapping_records()
    lines = [
        "This page is generated deterministically from `mappings/registry.json` and the registered mapping definitions. Edit the canonical mappings or registry, then regenerate this page.",
        "",
        f"Registry version: `{registry['registry_version']}`  ",
        f"Registry maturity: `{registry['maturity']}`",
        "",
        "| Mapping | Relationship | Transform | Maturity | Source | Target |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for record in records:
        mapping = record["mapping"]
        transform_kind = mapping.get("transform", {}).get("kind", "none")
        lines.append(
            f"| `{reference_text(mapping['mapping_id'])}` | `{mapping['relationship']}` | "
            f"`{transform_kind}` | `{mapping['maturity']}` | "
            f"`{reference_text(mapping['source']['contract'])}{mapping['source']['path']}` | "
            f"`{reference_text(mapping['target']['contract'])}{mapping['target']['path']}` |"
        )

    for record in records:
        entry = record["entry"]
        mapping = record["mapping"]
        transform = mapping.get("transform", {})
        lines.extend(
            [
                "",
                f"## {mapping['mapping_id']['id']}",
                "",
                f"- **ID:** `{reference_text(mapping['mapping_id'])}`",
                f"- **Version:** `{mapping['version']}`",
                f"- **Maturity:** `{mapping['maturity']}`",
                f"- **Relationship:** `{mapping['relationship']}`",
                f"- **Source:** `{reference_text(mapping['source']['contract'])}` at `{mapping['source']['path']}`",
                f"- **Target:** `{reference_text(mapping['target']['contract'])}` at `{mapping['target']['path']}`",
                f"- **Transform:** `{transform.get('kind', 'none')}`",
                f"- **Definition:** [`{entry['path']}`]({source_link(entry['path'])})",
            ]
        )
        if transform.get("description"):
            lines.extend(["", transform["description"]])
        if mapping.get("loss_notes"):
            lines.extend(["", f"**Known loss:** {mapping['loss_notes']}"])

    return lines


def render_schemas() -> str:
    lines = [HEADER, "", "# Schema Reference", "", *schema_reference_lines(repo_link)]
    return "\n".join(lines) + "\n"


def render_mappings() -> str:
    lines = [HEADER, "", "# Mapping Reference", "", *mapping_reference_lines(repo_link)]
    return "\n".join(lines) + "\n"


def render_starlight_schemas() -> str:
    lines = [
        "---",
        "title: Schema reference",
        "description: Generated reference for registered MeaningWire JSON Schema contracts.",
        "---",
        "",
        HEADER,
        "",
        *schema_reference_lines(public_source_link),
    ]
    return "\n".join(lines) + "\n"


def render_starlight_mappings() -> str:
    lines = [
        "---",
        "title: Mapping reference",
        "description: Generated reference for registered MeaningWire semantic mappings.",
        "---",
        "",
        HEADER,
        "",
        *mapping_reference_lines(public_source_link),
    ]
    return "\n".join(lines) + "\n"


def generated_documents() -> dict[Path, str]:
    return {
        OUTPUT_DIR / "schemas.md": render_schemas(),
        OUTPUT_DIR / "mappings.md": render_mappings(),
        STARLIGHT_OUTPUT_DIR / "schemas.md": render_starlight_schemas(),
        STARLIGHT_OUTPUT_DIR / "mappings.md": render_starlight_mappings(),
    }


def write_documents(documents: dict[Path, str]) -> None:
    for path, content in documents.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def check_documents(documents: dict[Path, str]) -> list[str]:
    errors: list[str] = []
    for path, expected in documents.items():
        relative = path.relative_to(ROOT)
        if not path.is_file():
            errors.append(f"missing generated reference: {relative}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"generated reference is stale: {relative}")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate MeaningWire reference Markdown")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed generated references are current without writing",
    )
    args = parser.parse_args(argv)

    try:
        documents = generated_documents()
        if args.check:
            errors = check_documents(documents)
            if errors:
                for error in errors:
                    print(f"ERROR: {error}")
                return 2
            print(f"PASS: {len(documents)} generated reference documents are current.")
            return 0
        write_documents(documents)
    except ReferenceGenerationError as exc:
        print(f"ERROR: {exc}")
        return 2

    print(f"PASS: generated {len(documents)} reference documents from canonical registries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
